name: ibans
description: Validate and parse IBAN strings and provide useful information about, such as country, bank name, number currency.
version: 0.0.1-alpha
homepage: https://github.com/iltoningui/ibans-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  protobuf: ^1.1.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
