name: ibans
description: A starting point for Dart libraries or applications.
version: 0.0.1-alpha
homepage: https://github.com/iltoningui/ibans-dart

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  protobuf: ^1.1.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
